--4
SELECT DISTINCT Dep.name FROM DOnations 
JOIN Departments AS Dep ON Dep.Id = Donations.department_id
JOIN SPONSORS AS S ON S.ID = DONATIONS.SPONSOR_ID 
WHERE S.NAME = 'XYZ Corporation';

--5
SELECT * FROM DOnations 
JOIN Departments AS Dep ON Dep.Id = Donations.department_id
JOIN SPONSORS AS S ON S.ID = DONATIONS.SPONSOR_ID
WHERE DONATIONS.DATE BETWEEN (CURRENT_DATE - INTERVAL '1 month') AND CURRENT_DATE

--6

SELECT DOCTORS.NAME, EXAMINATIONS.NAME, DEPARTMENTS.BUILDING FROM DOCTORS_EXAMINATIONS AS DE
JOIN DOCTORS ON DOCTORS.ID = DE.DOCTOR_ID
JOIN EXAMINATIONS ON EXAMINATIONS.ID = DE.EXAMINATION_ID
JOIN DEPARTMENTS ON DEPARTMENTS.ID = DE.DEPARTMENT_ID
WHERE EXAMINATIONS.DAYOFWEEK BETWEEN 1 AND 5

--7
SELECT DEPARTMENTS.NAME, DOCTORS.NAME FROM DOCTORS_EXAMINATIONS AS DE
JOIN DOCTORS ON DOCTORS.ID = DE.DOCTOR_ID
JOIN EXAMINATIONS ON EXAMINATIONS.ID = DE.EXAMINATION_ID
JOIN DEPARTMENTS ON DEPARTMENTS.ID = DE.DEPARTMENT_ID
JOIN DONATIONS ON DONATIONS.DEPARTMENT_ID = DE.DEPARTMENT_ID
WHERE DONATIONS.AMOUNT > 100000

--8
SELECT DEPARTMENTS.NAME FROM DOCTORS_EXAMINATIONS AS DE
JOIN DOCTORS ON DOCTORS.ID = DE.DOCTOR_ID
JOIN DEPARTMENTS ON DEPARTMENTS.ID = DE.DEPARTMENT_ID
WHERE DOCTORS.BONUS = 0

--9
  
SELECT DISTINCT Dp.Name AS Department, Ds.Name AS Disease
FROM Departments Dp
JOIN Doctors_Examinations AS DE ON Dp.Id = DE.Department_id
JOIN Examinations AS E ON DE.Examination_Id = E.Id
JOIN ExaminationDates AS ED ON E.Id = ED.ExaminationId
JOIN Diseases Ds ON E.Id = Ds.Id
WHERE ED.ExaminationDate >= CURRENT_DATE - INTERVAL '6 months';


